global using Microsoft.EntityFrameworkCore;
global using FluentValidation;
global using System.Reflection;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.DependencyInjection;
global using MediatR;
global using Microsoft.Extensions.Logging;

global using Ordering.Domain.Enums;
global using Ordering.Application.Dtos;
global using SharedKernel.CQRS;
global using Ordering.Domain.Models;
global using Ordering.Application.Data;
global using Ordering.Domain.ValueObjects;
global using SharedKernel.Exceptions;
global using Ordering.Application.Exceptions;
global using SharedKernel.Behaviors;
global using Ordering.Domain.Events;
global using Ordering.Application.Extensions;